# Fichier de configuration pour Nixpacks (utilisé par Railway)
# https://nixpacks.com/docs/configuration/file

[phases.setup]
# Installe les extensions PHP nécessaires pour l'application.
# La version de PHP (ici php82) doit correspondre à celle de votre projet.
nixPkgs = ["php82Extensions.pdo_mysql", "php82Extensions.mysqli", "php82Extensions.curl"]

[start]
# Commande pour démarrer le serveur Apache avec le dossier courant comme racine.
cmd = "heroku-php-apache2 ."